version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/cync-controller"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/python-rebuild-tcp-comm"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "docker"
    directory: "/cync-controller"
    schedule:
      interval: daily
      time: "08:00"

  - package-ecosystem: "docker"
    directory: "/.cursor"
    schedule:
      interval: daily
      time: "08:00"
